### ISSUE TITLE
SOLR secureComms secret configured without shared secret value

### ISSUE THREAD

**Issue by jalvarezferr** [Alfresco/alfresco-ansible-deployment#774]
#### Bug description

When installing release 7.2 or higher, the playbooks configure SOLR secureComms communication mode both in alfresco-global.properties and solrcore.properties, but do not configure a shared secret value.

Somehow Alfresco does use the `X-Alfresco-Search-Secret property` header with a value that is accepted by SOLR administration API, as our tcpdump inspection showed. However, that value does not seem to exist in any configuration, and as said, it is surely not in the properties files as expected.

This impedes access to the SOLR administration console for ordinary troubleshooting and administration, as well as using the API for automation or monitoring purposes.

It is unclear how this secureComms mode improves security over the already in place basic authentication, that in effect does implement a header that is used to pass a secret value (the base64 username:password in that case). We'd rather have this mode be optional by providing or not a secret to the playbooks.

#### Target OS

Any

#### Host OS

Any

#### Playbook version

2.0.0+

#### Ansible error

None

#### Ansible context

None

##### ansible --version

Not relevant

##### ansible-config dump --only-changed

Not relevant

##### ansible-inventory -i your_inventory_file --graph

Not relevant

##### pip list

Not relevant

**Comment by alxgomz** [comment]
Hi @jalvarezferr ,

Indeed the solr/repo shared secret is not set in properties file. This is actually by design and - if I remember correctly - Solr will not even try to  get that property from its properties file (so it would be useless to add it there).
Instead the corresponding system property is passed to the JVM using the `JAVA_TOOL_OPTIONS` env var both in repo and solr (from the top of my head you should find it either in the startup script or the systemd unit file).

This header has been added in order to protect the full Solr API, not just the admin api like the basic auth does (I'm assuming you're talking about the basic auth set at the proxy level?). Though, I admit that having this kind of double auth on the admin may not be convenient but this is something that would need to be raised with the product team, not really deployment. I would encourage you to reach out to support if your are a customer otherwise maybe raise an issue in the [Alfresco search project](https://github.com/Alfresco/SearchServices/). The [Alfresco Discord](https://discordapp.com/channels/451644531323174912/451644531323174914) can also be a good source of info and @aborroy is always hanging over there.

Finally starting from 7.2, Alfresco do not allow `securecomms=none` anymore. One has to choose between the header based auth (`securecomms=secret`) or the mutual TLS authentication (`securecomms=https`). Agai this is a desingn choice to prevent unauthorized access to the Solr search api thus preventing content leaks.

I hope that helps.
