### ISSUE TITLE
Incorrect TRouter handlers order

### ISSUE THREAD

**Issue by dxciberaws** [Alfresco/alfresco-ansible-deployment#890]
In the `trouter` role, the `Wait-for-aio` handler is declared first, before the ones that enable and start the service. Hence, the `Add alfresco-transform-router service` task that has all three of them, starts by waiting for the tcp port to be open before enabling or starting the service, which does not happen as the service was not started.

https://github.com/Alfresco/alfresco-ansible-deployment/blob/d43f81f3da137f81650d87b8aee11f7b280aeda2/roles/trouter/handlers/main.yml#L3

For some reason I still have not found out, this worked on previous CentOS systems we used before, probably because the preceding tasks notify the `Restart-trouter` handler and in those systems that started the service even if not enabled. We are now testing Amazon Linux and in these the behavior changed and the service is not started.

Other roles, like the `sync` one that also use this same handlers scheme, have them declared in the correct way.

We applied the fix, placing the handler last in the file and tested it successfully.

**Comment by gionn** [comment]
Hello @dxciberaws, the `wait-for-aio` handler is checking that the All-In-One transformer service is up and running, not the Transform Router.

When you run the acs.yml playbook, `transformers` role is being applied before the `trouter` role, so it should never happen that the `wait-for-aio` fails because the service has not started yet.

If you are seeing a different behavior on Amazon Linux maybe that's related to another issue/possible bug.

Also keep in mind that despite Amazon Linux is a [supported Alfresco platform](https://docs.alfresco.com/content-services/latest/support/), [playbooks doesn't](https://alfresco.github.io/alfresco-ansible-deployment/overview.html#versioning).
Anyway we could still consider PRs in case you find and fix some issues.

Thanks anyway for taking time to report this.
