### ISSUE TITLE
Default inventory requires change to work with community edition

### ISSUE THREAD

**Issue by RTheren** [Alfresco/alfresco-ansible-deployment#907]
#### Bug description

After running the ansible-playbook with arguments for local deployment (pipenv run ansible-playbook playbooks/acs.yml -i inventory_local.yml -e "@community-extra-vars.yml"), I tried accessing the service via HTTPS and it died few seconds after trying to login (which it complained that it couldn't authenticate). 
Digging through the alfresco logs, I only found a mention of missing "elasticsearch" beans from Tomcat, and typical Java errors.
After many hours of looking at documentation and extensive search, I looked at our test instance in Docker, and I noticed when comparing the two that ansible didn't deploy Solr search engine. 
After looking at inventory_local.yml, I tried adding repository: variable and re-ran it. 
Afterwards, the Alfresco service ran without any noticeable problem.

So the part in inventory_local.yml looked like this in the end:
```
    # Solr search engine (alternative to Enterprise Search)
    search:
      children:
        repository:
```

#### Target OS

AlmaLinux 9 (tried it here first, but changed to RockyLinux since AL is not officially supported)
RockyLinux 9 (final deployment)

#### Host OS

RockyLinux 9

#### Playbook version

v2.9.0

#### Ansible error

No error, deployment was successful. The Solr parts were marked as [Skipped]

##### ansible --version

```shell
ansible [core 2.15.11]
  config file = /root/alfresco-ansible-deployment/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/share/virtualenvs/alfresco-ansible-deployment-qhTOnLa5/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/share/virtualenvs/alfresco-ansible-deployment-qhTOnLa5/bin/ansible
  python version = 3.9.18 (main, May 16 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/root/.local/share/virtualenvs/alfresco-ansible-deployment-qhTOnLa5/bin/python)
  jinja version = 3.1.4
  libyaml = True

```

##### ansible-config dump --only-changed

```shell
ANSIBLE_PIPELINING(/root/alfresco-ansible-deployment/ansible.cfg) = True
CONFIG_FILE() = /root/alfresco-ansible-deployment/ansible.cfg
```

##### ansible-inventory -i your_inventory_file --graph

```shell
@all:
  |--@ungrouped:
  |--@repository:
  |  |--localhost
  |--@database:
  |  |--@repository:
  |  |  |--localhost
  |--@activemq:
  |  |--@repository:
  |  |  |--localhost
  |--@search:
  |  |--@repository:
  |  |  |--localhost
  |--@search_enterprise:
  |  |--@repository:
  |  |  |--localhost
  |--@elasticsearch:
  |  |--@repository:
  |  |  |--localhost
  |--@identity:
  |--@nginx:
  |  |--@repository:
  |  |  |--localhost
  |--@acc:
  |  |--@repository:
  |  |  |--localhost
  |--@adw:
  |  |--@repository:
  |  |  |--localhost
  |--@transformers:
  |  |--@repository:
  |  |  |--localhost
  |--@syncservice:
  |  |--@repository:
  |  |  |--localhost
  |--@other_repo_clients:
  |--@trusted_resource_consumers:
  |  |--@repository:
  |  |  |--localhost
  |  |--@nginx:
  |  |  |--@repository:
  |  |  |  |--localhost
  |  |--@adw:
  |  |  |--@repository:
  |  |  |  |--localhost
  |  |--@other_repo_clients:
  |--@external_activemq:
  |--@external_elasticsearch:
  |--@external_identity:
  |--@external:
  |  |--@external_activemq:
  |  |--@external_elasticsearch:
  |  |--@external_identity:
  |  |--@other_repo_clients:
```

##### pip list

```shell
Package             Version
------------------- -------
ansible-core        2.15.11
cffi                1.16.0
cryptography        42.0.5
importlib-resources 5.0.7
Jinja2              3.1.4
jmespath            1.0.1
MarkupSafe          2.1.5
packaging           24.0
pip                 24.1
pycparser           2.22
PyYAML              6.0.1
resolvelib          1.0.1
setuptools          70.1.0
wheel               0.43.0
```

**Comment by gionn** [comment]
Hello @RTheren, thanks for reporting this.

It looks like installing the community version with one of the inventories we provide (like [local](https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/inventory_local.yml) is broken since [v2.6.0](https://github.com/Alfresco/alfresco-ansible-deployment/releases/tag/v2.6.0) when we switched the default search backend to search enterprise (which of course is available only with the enterprise version).

So we should either provide a dedicated inventory for community, or assert in the playbook that at least one search group contains an host or some other combination to make sure at least an host in the `search` group is present when installing community.

**Comment by RTheren** [comment]
Thanks for reporting it internally. Hopefully someone else reading this can avoid possible headache until this is fixed. :)

**Comment by alsareti** [comment]
Hello @gionn,
 the problem arises from Playbook version v2.6.0 (ACS 23.2.1) and any subsequent versions, up to the latest version 2.9.0.

**Comment by gionn** [comment]
Now the playbook explicitly checks that the inventory doesn't contains any hosts in the search_enterprise group when installing the community edition, so at least it will be easier to discover that such configuration can't be supported.

**Comment by alsareti** [comment]
> Now the playbook explicitly checks that the inventory doesn't contains any hosts in the search_enterprise group when installing the community edition, so at least it will be easier to discover that such configuration can't be supported.

After installing ACS 23.2.0, the following error message was encountered during the first attempts:
 
<details><summary>Message</summary>
<p>
Your inventory includes one or more hosts in the search-enterprise group, which is not a supported configuration for the community edition.
 Please remove the hosts from the search-enterprise group and ensure that the search group contains at least one host.
</p>
</details> 
After **updating** the "inventory_local.yml" file with the below configuration for Solr search engine, the issue was resolved

```python
 # Solr search engine (an alternative to Enterprise Search, and the only available option for the Community edition)
    search:
      children:
        repository:

    # Enterprise Search (default search engine - not available in Community edition)
    search_enterprise:
      children:
        #vrepository:
    elasticsearch:
      children:
        # repository:
```


 Subsequently, various functionalities such as upload, download, and search were tested and found to be **_working properly_**.
